package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Acta_comite_directivo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Acta_comite_directivo() {
    }




}