package com.myspace.direcgeneral;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Correos_Sugerencias implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Correos_Sugerencias() {
    }




}